# Generated by Django 6.0 on 2025-12-27 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='sent_at',
            new_name='created_at',
        ),
    ]
