# Generated by Django 6.0 on 2025-12-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_rename_sent_at_contactmessage_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_name', models.CharField(max_length=100)),
                ('learner_surname', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('id_number', models.CharField(max_length=13)),
                ('parent_name', models.CharField(max_length=150)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_contact', models.CharField(max_length=20)),
                ('learner_contact', models.CharField(max_length=20)),
                ('home_address', models.TextField()),
                ('province', models.CharField(max_length=50)),
                ('previous_school', models.CharField(max_length=150)),
                ('career', models.CharField(max_length=150)),
                ('motivation', models.TextField()),
                ('learner_signature', models.CharField(max_length=150)),
                ('parent_signature', models.CharField(max_length=150)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
