# Generated by Django 6.0 on 2025-12-27 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='home_address',
        ),
        migrations.AddField(
            model_name='application',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='applications/id_documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='career',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='learner_signature',
            field=models.ImageField(blank=True, null=True, upload_to='applications/signatures/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='parent_signature',
            field=models.ImageField(blank=True, null=True, upload_to='applications/signatures/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='previous_school',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='province',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
