# Generated by Django 6.0 on 2025-12-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_remove_application_home_address_application_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='home_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
